# Generated by Django 4.1.2 on 2022-10-09 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='familiar',
            name='fecha_nacimiento',
        ),
    ]
