# Generated by Django 4.1.2 on 2022-10-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0002_remove_familiar_edad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='edad',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='familiar',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
