# Generated by Django 4.1.2 on 2022-10-09 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0003_familiar_edad_familiar_fecha_nacimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familiar',
            old_name='fecha_nacimiento',
            new_name='fecha',
        ),
    ]
